// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzwdeydawwnmbucqeuxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6d2RleWRhd3dubWJ1Y3FldXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3OTYzMTQsImV4cCI6MjA1MDM3MjMxNH0.9BnNpIKlkbj-yQc67asrGsACHX-ZbUHmiQRHLaAEFLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);